apiVersion: v1
kind: Service
metadata:
  name: skillful-vaishali-5e5ef3b2d7-srv
  namespace: apps-dev
spec:
  selector:
    app: skillful-vaishali-5e5ef3b2d7
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP